# Generated by Django 5.2.16 on 2026-07-25 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('is_open', models.BooleanField(default=True, help_text='Czy użytkownicy mogą oddawać i zmieniać głosy na okręgi tego urzędu.', verbose_name='głosowanie otwarte')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'urząd',
                'verbose_name_plural': 'urzędy',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nazwa')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('seats_count', models.PositiveIntegerField(default=1, help_text='Ile mandatów obsadzanych jest w tym okręgu (metoda Schulzego).', verbose_name='liczba mandatów')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('territorial_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electoral_districts', to='geo.territorialunit', verbose_name='jednostka terytorialna')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='elections.office', verbose_name='urząd')),
            ],
            options={
                'verbose_name': 'okręg wyborczy',
                'verbose_name_plural': 'okręgi wyborcze',
                'ordering': ['office__display_order', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectionResultCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict, verbose_name='wynik')),
                ('ballot_count', models.PositiveIntegerField(default=0, verbose_name='liczba głosów')),
                ('fingerprint', models.CharField(blank=True, max_length=64, verbose_name='odcisk głosów')),
                ('is_stale', models.BooleanField(default=True, verbose_name='wymaga przeliczenia')),
                ('computed_at', models.DateTimeField(blank=True, null=True, verbose_name='wyliczono')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_cache', to='elections.electoraldistrict', verbose_name='okręg')),
            ],
            options={
                'verbose_name': 'cache wyniku',
                'verbose_name_plural': 'cache wyników',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='imię i nazwisko')),
                ('bio', models.TextField(blank=True, verbose_name='biogram')),
                ('is_active', models.BooleanField(default=True, help_text='Nieaktywni kandydaci nie biorą udziału w nowych głosowaniach.', verbose_name='aktywny')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='kolejność wyświetlania')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.electoraldistrict', verbose_name='okręg')),
            ],
            options={
                'verbose_name': 'kandydat',
                'verbose_name_plural': 'kandydaci',
                'ordering': ['district', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VoterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polling_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='geo.pollingstation', verbose_name='komisja wyborcza')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voter_profile', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'profil wyborcy',
                'verbose_name_plural': 'profile wyborców',
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.JSONField(default=list, help_text='Uporządkowana lista ID kandydatów (od najlepszego do najgorszego).', verbose_name='ranking')),
                ('is_voided', models.BooleanField(db_index=True, default=False, help_text='Głos zamrożony (np. po zmianie komisji poza zasięgiem okręgu).', verbose_name='unieważniony / zawieszony')),
                ('void_reason', models.CharField(blank=True, choices=[('CHANGE_OF_POLLING_STATION', 'Zmiana komisji wyborczej')], default='', max_length=64, verbose_name='powód unieważnienia')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='unieważniono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Aktualizowane przy każdej zmianie głosu.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='elections.electoraldistrict', verbose_name='okręg')),
            ],
            options={
                'verbose_name': 'głos',
                'verbose_name_plural': 'głosy',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'district'), name='unique_ballot_per_user_district')],
            },
        ),
    ]
