# Generated by Django 5.2.16 on 2026-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ballot",
            old_name="ranking",
            new_name="ranked_candidate_ids",
        ),
        migrations.AlterField(
            model_name="ballot",
            name="ranked_candidate_ids",
            field=models.JSONField(
                default=list,
                help_text=(
                    "Lista ID kandydatów od najwyżej preferowanego. "
                    "Pozostali kandydaci okręgu = nieuporządkowani (unranked)."
                ),
                verbose_name="uporządkowani kandydaci",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="committee",
            field=models.CharField(
                blank=True,
                help_text="Nazwa komitetu wyborczego (opcjonalnie).",
                max_length=200,
                verbose_name="komitet",
            ),
        ),
    ]
