# Generated by Django 4.2.27 on 2026-07-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_precinct_kind_polling_station'),
        ('elections', '0005_remove_candidate_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballot',
            name='ranked_candidate_ids',
        ),
        migrations.RemoveField(
            model_name='electoraldistrict',
            name='territorial_unit',
        ),
        migrations.RemoveField(
            model_name='office',
            name='requires_local_residence',
        ),
        migrations.AddField(
            model_name='ballot',
            name='ranked_user_ids',
            field=models.JSONField(default=list, help_text='Lista ID użytkowników od najwyżej preferowanego. Pozostali uprawnieni użytkownicy okręgu = nieuporządkowani (unranked).', verbose_name='ranking użytkowników'),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=18, help_text='Minimalny wiek (w latach) wymagany do głosowania i kandydowania w tym okręgu.', verbose_name='minimalny wiek'),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='territorial_units',
            field=models.ManyToManyField(blank=True, help_text='Węzły hierarchii należące do tego okręgu. Wyborca jest uprawniony, gdy jego obwód leży w poddrzewie któregoś z tych węzłów.', related_name='electoral_districts', to='geo.territorialunit', verbose_name='jednostki terytorialne'),
        ),
        migrations.AddField(
            model_name='voterprofile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Wymagana do weryfikacji limitu wieku w okręgu wyborczym.', null=True, verbose_name='data urodzenia'),
        ),
        migrations.AddField(
            model_name='voterprofile',
            name='territorial_unit',
            field=models.ForeignKey(blank=True, help_text='Węzeł hierarchii, z którym powiązany jest wyborca. Minimum: kraj. Jeśli ustawiona komisja, obwód komisji jest używany do wyznaczenia uprawnień.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='geo.territorialunit', verbose_name='jednostka terytorialna'),
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='polling_station',
            field=models.ForeignKey(blank=True, help_text='Wymagana do głosowania. Komisja musi należeć do obwodu będącego potomkiem territorial_unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='geo.pollingstation', verbose_name='komisja wyborcza'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
