# Generated by Django 5.2.16 on 2026-07-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_district_m2m_units_min_age_ballot_user_ids'),
        ('geo', '0006_precinct_kind_polling_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterprofile',
            name='polling_station',
        ),
        migrations.AlterField(
            model_name='voterprofile',
            name='territorial_unit',
            field=models.ForeignKey(blank=True, help_text='Węzeł hierarchii wyborcy. Minimum: kraj. Do głosowania wymagany obwód wyborczy (kind=precinct).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='geo.territorialunit', verbose_name='jednostka terytorialna'),
        ),
    ]
