# Generated by Django 4.2.27 on 2026-07-27 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0010_voterprofile_phone_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Opcjonalny numer w formacie +48XXXXXXXXX.', max_length=16, null=True, unique=True, verbose_name='telefon'),
        ),
        migrations.CreateModel(
            name='CandidateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='imię')),
                ('last_name', models.CharField(max_length=150, verbose_name='nazwisko')),
                ('birth_date', models.DateField(verbose_name='data urodzenia')),
                ('note', models.TextField(blank=True, verbose_name='uwaga dla admina')),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('approved', 'Zatwierdzona'), ('rejected', 'Odrzucona')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('admin_note', models.TextField(blank=True, verbose_name='notatka admina')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='rozpatrzono')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_candidate_requests', to=settings.AUTH_USER_MODEL, verbose_name='utworzony użytkownik')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_requests', to='elections.electoraldistrict', verbose_name='okręg')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_requests', to=settings.AUTH_USER_MODEL, verbose_name='zgłaszający')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidate_requests', to=settings.AUTH_USER_MODEL, verbose_name='rozpatrzył')),
            ],
            options={
                'verbose_name': 'prośba o kandydata',
                'verbose_name_plural': 'prośby o kandydatów',
                'ordering': ['-created_at'],
            },
        ),
    ]
