# Generated by Django 6.0.7 on 2026-07-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0011_candidate_request_and_optional_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='voterprofile',
            name='second_name',
            field=models.CharField(blank=True, default='', help_text='Opcjonalne drugie imię.', max_length=150, verbose_name='drugie imię'),
        ),
    ]
