# Generated by Django 5.2.16 on 2026-07-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingstation',
            options={'ordering': ['number', 'name'], 'verbose_name': 'komisja wyborcza', 'verbose_name_plural': 'komisje wyborcze'},
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Numer obwodu głosowania (np. z PKW).', null=True, verbose_name='numer komisji'),
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='streets_served',
            field=models.TextField(blank=True, help_text='Opis ulic / granic obwodu obsługiwanych przez komisję.', verbose_name='obsługiwane ulice'),
        ),
    ]
