# Generated by Django 4.2.27 on 2026-07-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0005_polling_station_served_districts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollingstation',
            name='served_districts',
        ),
        migrations.RemoveField(
            model_name='pollingstation',
            name='served_units',
        ),
        migrations.RemoveField(
            model_name='pollingstation',
            name='territorial_unit',
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='precinct',
            field=models.ForeignKey(blank=True, help_text='Obwód wyborczy (węzeł w hierarchii), do którego należy komisja.', limit_choices_to={'kind': 'precinct'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polling_stations', to='geo.territorialunit', verbose_name='obwód wyborczy'),
        ),
        migrations.AlterField(
            model_name='territorialunit',
            name='kind',
            field=models.CharField(choices=[('country', 'Kraj'), ('voivodeship', 'Województwo'), ('county', 'Powiat'), ('district', 'Okręg wyborczy (przestarzałe)'), ('municipality', 'Gmina'), ('precinct', 'Obwód wyborczy')], max_length=20, verbose_name='rodzaj'),
        ),
    ]
